const PERMISSIONS = {
  CREATE_POST: "CREATE_POST",
  READ_OWN_POST: "READ_OWN_POST",
  READ_PUBLIC_POST: "READ_PUBLIC_POST",
  READ_ANY_POST: "READ_ANY_POST",
  UPDATE_OWN_POST: "UPDATE_OWN_POST",
  UPDATE_ANY_POST: "UPDATE_ANY_POST",
  DELETE_OWN_POST: "DELETE_OWN_POST",
  DELETE_ANY_POST: "DELETE_ANY_POST",
  SEND_NOTIFICATION: "SEND_NOTIFICATION",
};

export default PERMISSIONS;
